### ISSUE TITLE
Click bug fix?

### ISSUE THREAD

**Issue by NycuRO** [Muqsit/BedrockFix#1]
Can you fix click bug?

**Comment by Muqsit** [comment]
That one is impossible to fix, you'll need let mojang do it sadly.

**Comment by NycuRO** [comment]
NukkitX already fixed lol.

**Comment by Muqsit** [comment]
There's no appropriate fix for it. If anyone managed to fix it, they probably introduced a worse bug.

**Comment by NycuRO** [comment]
Nah, just see this commit, they actually works so good: https://github.com/NukkitX/Nukkit/commit/52141a74b71d69e58ce12fe9e6b38f8453056970

**Comment by Muqsit** [comment]
Yeah, it doesn't work lol.

**Comment by NycuRO** [comment]
You tested?

**Comment by Muqsit** [comment]
I don't think you get it. It's not that simple to fix it. You're just creating even more bugs by skipping.
