### ISSUE TITLE
Nametag Bug still there

### ISSUE THREAD

**Issue by MSG100TC** [Muqsit/BedrockFix#4]
Hello, the name tag of players were still white even I have the plugin loaded correctly, it is listed in /pl

Using pmmp 3.1.1, latest stable phar.

**Comment by MSG100TC** [comment]
I think have a solution.

**Comment by MSG100TC** [comment]
Nope, still bugged. Help needed

**Comment by MSG100TC** [comment]
The last commit still didn't fix the name tags. White it is.

**Comment by MSG100TC** [comment]
Any updates on the name tag fix? The last commit still shows the broken-white name tag

**Comment by MSG100TC** [comment]
In the latest update the name tag was normal for a split second but back to white after, and it doesn't show name tag when you are far away from the player

**Comment by FreeGamingHere** [comment]
Same issue here, I get undefined index errors. You have to add the $player->eid to the array. @Muqsit

**Comment by Muqsit** [comment]
Fixed in the latest commit.
