### ISSUE TITLE
Error when join in server

### ISSUE THREAD

**Issue by alair069** [Muqsit/BedrockFix#6]
``[21:33:06] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\server\DataPacketSendEvent' to 'BedrockFix v0.0.1-dev': Undefined offset: 1 on muqsit\bedrockfix\EventListener
[21:33:06] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 1" (EXCEPTION) in "plugins/BedrockFix-master/src/muqsit/bedrockfix/EventListener" at line 69``

**Comment by edwinyoo44** [comment]
[Server thread/CRITICAL]: 無法處理事件 'pocketmine\event\player\PlayerMoveEvent' 至 'BedrockFix v0.0.1-dev'：Call to a member function getCollisionCubes() on null 在 muqsit\bedrockfix\EventListener 上
[Server thread/CRITICAL]: Error: "Call to a member function getCollisionCubes() on null" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1495
[Server thread/DEBUG]: #0 plugins/BedrockFix-master/src/muqsit/bedrockfix/EventListener(86): pocketmine\entity\Entity->fastMove(double -25.1909, double 0, double 44.635)
[Server thread/DEBUG]: #1 src/pocketmine/plugin/MethodEventExecutor(38): muqsit\bedrockfix\EventListener->onPlayerMove(pocketmine\event\player\PlayerMoveEvent object)
[Server thread/DEBUG]: #2 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(muqsit\bedrockfix\EventListener object, pocketmine\event\player\PlayerMoveEvent object)
[Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(749): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerMoveEvent object)
[Server thread/DEBUG]: #4 src/pocketmine/Player(1593): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerMoveEvent object)
[Server thread/DEBUG]: #5 src/pocketmine/Player(1700): pocketmine\Player->processMovement(integer 1)
[Server thread/DEBUG]: #6 src/pocketmine/level/Level(743): pocketmine\Player->onUpdate(integer 5297)
[Server thread/DEBUG]: #7 src/pocketmine/Server(2359): pocketmine\level\Level->doTick(integer 5297)
[Server thread/DEBUG]: #8 src/pocketmine/Server(2516): pocketmine\Server->checkTickUpdates(integer 5297, double 1533305039.6914)
[Server thread/DEBUG]: #9 src/pocketmine/Server(2258): pocketmine\Server->tick()
[Server thread/DEBUG]: #10 src/pocketmine/Server(2132): pocketmine\Server->tickProcessor()
[Server thread/DEBUG]: #11 src/pocketmine/Server(1713): pocketmine\Server->start()
[Server thread/DEBUG]: #12 src/pocketmine/PocketMine(237): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/edwinyoo44/mcpe/, string /home/edwinyoo44/mcpe/plugins/)

**Comment by Muqsit** [comment]
https://github.com/Muqsit/BedrockFix/issues/5
