### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shdudwns** [Muqsit/BedrockFix#7]
CRITICAL]: 이벤트 'pocketmine\event\player\PlayerMoveEvent'을(를) 'BedrockFix v0.0.1-dev'에 전달할 수 없습니다: muqsit\bedrockfix\EventListener에서의 Call to a member function getCollisionCubes() on null
[17:50:31] [Server thread/CRITICAL]: Error: "Call to a member function getCollisionCubes() on null"

**Comment by artulloss** [comment]
As Muqsit said, there is a plugin calling Entity->close();
